### jwt login
POST http://localhost:9000/auth-service/login
Content-Type: application/json

{
  "username": "test1",
  "password": "password1"
}

> {%
    client.global.set("jwt", `Bearer ${response.headers.valueOf('Authorization')}`);
%}

### chat
POST http://localhost:9000/chat-service/llm/chat
Content-Type: application/json
Authorization: {{jwt}}

{
  "request": "요청1",
  "model": "GEMINI_2_0_FLASH"
}

### chat
POST http://localhost:9000/chat-service/llm/stream
Content-Type: application/json
Authorization: {{jwt}}

{
  "request": "요청2",
  "model": "GEMINI_2_0_FLASH"
}