server:
  port: 9000

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
#      routes:
#        - id: auth-service
#          uri: http://localhost:9001
#          predicates:
#            - Path=/auth/**
#          filters:
#            - RewritePath=/auth/(?<path>.*), /${path}
#        - id: chat-service
#          uri: http://localhost:9002
#          predicates:
#            - Path=/chat/**

jwt:
  secret: bm9kLW5vZC1qd3QtdG9rZW4tc2VjcmV0LW5vZC1ub2Qtand0LXRva2VuLXNlY3JldA==
  access:
    seconds: 1800 #초 30분